[package]
name = "tex_engine"
version = "0.0.1"
edition = "2021"
authors = ["Dennis Müller <d.mueller@kwarc.info>"]
description = "A modular crate for building TeX engines"
readme = "README.md"
repository = "https://github.com/Jazzpirate/RusTeX/tree/main/tex_engine"
license = "GPL-3.0-or-later"
keywords = ["tex", "latex","rustex"]
categories = ["compilers","data-structures"]
exclude = [".idea/*","build.rs","resources/*","target/*"]

[lib]
crate-type = ["lib"]
path = "src/lib.rs"

[profile.dev]
#opt-level = 3
#lto = true
#debug = 2
#split-debuginfo = "off"
#strip = "none"

[profile.release]
opt-level = 3
lto = true
debug = 2

[features]
default = []
pdflatex = ["md5"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#[build-dependencies]
#bindgen = "0.59"
#pkg-config = "0.3"

[dev-dependencies]
env_logger = "0.10.0"
rand = "0.8.5"
ansi_term = "0.12.1"

[dependencies]
lazy_static = "1.4.0"
log={version="0.4.20",features=["kv_unstable"]}
ahash = "0.8.6"
string-interner = "0.14.0"
#rand = "0.8.5"
#paste="1.0.13"
chrono = "0.4.31"
array-init = "2.1.0"
arrayvec = "0.7.4"
shared_vector = "0.4.4"
regex = "1.10.2"
#image = "0.24.7"
#pdfium-render = "0.8.11" #, features = ["static"] }

md5 = { version = "0.7.0",optional = true }


#hashbrown = {version="0.14.0",features=["raw"]}
#interned = "0.1.1"
#staticize = "0.1.1"
#bumpalo = {version ="3.13.0", features = ["collections"]}
#blink-alloc = "0.3.0"
#allocator-api2 = "0.2.16"
#include_dir = "0.7.3"
#base64 =  "0.21.0"
#clap = { version = "4.1.4", features = ["derive"] }
# serde = { version = "1.0.183", features = ["derive"] }