[package]
name = "tex_engine"
version = "0.0.1"
edition = "2021"
authors = ["Dennis Müller <d.mueller@kwarc.info>"]
description = "A modular crate for building TeX engines"
readme = "README.md"
repository = "https://github.com/Jazzpirate/RusTeX/tree/main/tex_engine"
license = "GPL-3.0-or-later"
keywords = ["tex", "latex","rustex"]
categories = ["compilers","data-structures"]
exclude = [".idea/*","build.rs","resources/*","target/*"]

[lib]
crate-type = ["lib"]
path = "src/lib.rs"

[profile.release]
opt-level = 3
lto = true
debug = 1

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#[build-dependencies]
#bindgen = "0.59"
#pkg-config = "0.3"

[dev-dependencies]
env_logger = "0.10.0"

[dependencies]
paste="1.0.13"
lazy_static = "1.4.0"
ansi_term = "0.12.1"
chrono = "0.4.23"
log={version="0.4.19",features=["kv_unstable"]}
ahash = "0.8.3"
hashbrown = {version="0.14.0",features=["raw"]}
# string-interner = "0.14.0"
#interned = "0.1.1"
#staticize = "0.1.1"
#bumpalo = {version ="3.13.0", features = ["collections"]}
#arrayvec = "0.7.4"
#blink-alloc = "0.3.0"
#allocator-api2 = "0.2.16"
#include_dir = "0.7.3"
#regex = "1.7.1"
#md5 = "0.7.0"
#image = "0.24.5"
#base64 =  "0.21.0"
#clap = { version = "4.1.4", features = ["derive"] }
#pdfium-render = "0.8.1" #, features = ["static"] }
# serde = { version = "1.0.183", features = ["derive"] }