name: Test
on: [push]
jobs:
  test_tex_engine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: TeXLive
        run: sudo apt install texlive-full
  #    - name: Packages
  #      run: tlmgr init-usertree && tlmgr install article geometry xcolor amsmath graphicx stex wrapfig mdframed listings tcolorbox
      - name: rustup
        run: rustup update && rustup toolchain install nightly
      - name: Test tex_engine
        run: cd tex_engine && cargo test --features pdflatex
  test_tex_tfm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: TeXLive
        run: sudo apt install texlive-base
      - name: Test tex_tfm
        run: cd tex_tfm && cargo test
  test_rustex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: TeXLive
        run: sudo apt install texlive-full
      - name: Test rustex
        run: cd rustex && cargo test